apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::242616060700:user/ctse-test
      username: ctse-test
      groups:
        - deployment-ctse