apiVersion: v1
kind: Service
metadata:
  name: nginx-app-api-service
spec:
  selector:
    app: nginx-app-products-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP